import re

with open('/Users/nguyetpham/.gemini/antigravity/brain/6f9a1aaa-e3ba-4490-a52a-ca067528b732/scratch/extract_vocab.py', 'r', encoding='utf-8') as f:
    text = f.read()

# I will replace the verbs with their base forms
replacements = {
    '"measured": "được đo lường"': '"measure": "đo lường"',
    '"evaluated": "được đánh giá"': '"evaluate": "đánh giá"',
    '"assessed": "được đánh giá"': '"assess": "đánh giá"',
    '"analyzed": "được phân tích"': '"analyze": "phân tích"',
    '"investigated": "được điều tra"': '"investigate": "điều tra"',
    '"examined": "được kiểm tra"': '"examine": "kiểm tra"',
    '"inspected": "được thanh tra"': '"inspect": "thanh tra"',
    '"reviewed": "được xem xét"': '"review": "xem xét"',
    '"surveyed": "được khảo sát"': '"survey": "khảo sát"',
    '"interviewed": "được phỏng vấn"': '"interview": "phỏng vấn"',
    '"questioned": "bị chất vấn"': '"question": "chất vấn, đặt câu hỏi"',
    '"answered": "được trả lời"': '"answer": "trả lời"',
    '"responded": "đã phản hồi"': '"respond": "phản hồi"',
    '"replied": "đã trả lời"': '"reply": "đáp lại"',
    '"commented": "đã bình luận"': '"comment": "bình luận"',
    '"stated": "đã tuyên bố"': '"state": "tuyên bố, phát biểu"',
    '"declared": "đã tuyên bố"': '"declare": "tuyên bố"',
    '"announced": "đã thông báo"': '"announce": "thông báo"',
    '"reported": "đã báo cáo"': '"report": "báo cáo"',
    '"mentioned": "đã đề cập"': '"mention": "đề cập"',
    '"noted": "đã ghi chú"': '"note": "ghi chú, lưu ý"',
    '"recorded": "đã ghi lại"': '"record": "ghi lại"',
    '"documented": "được ghi chép"': '"document": "ghi chép, lập tài liệu"',
    '"published": "được xuất bản"': '"publish": "xuất bản"',
    '"printed": "được in"': '"print": "in ấn"',
    '"broadcast": "được phát sóng"': '"broadcast": "phát sóng"',
    '"televised": "được truyền hình"': '"televise": "truyền hình"',
    '"screened": "được chiếu"': '"screen": "chiếu phim, kiểm tra"',
    '"displayed": "được hiển thị"': '"display": "hiển thị, trưng bày"',
    '"exhibited": "được triển lãm"': '"exhibit": "triển lãm"',
    '"presented": "được trình bày"': '"present": "trình bày, tặng"',
    '"demonstrated": "được chứng minh"': '"demonstrate": "chứng minh, biểu diễn"',
    '"illustrated": "được minh họa"': '"illustrate": "minh họa"',
    '"explained": "được giải thích"': '"explain": "giải thích"',
    '"clarified": "được làm rõ"': '"clarify": "làm rõ"',
    '"simplified": "được đơn giản hóa"': '"simplify": "đơn giản hóa"',
    '"misunderstood": "bị hiểu lầm"': '"misunderstand": "hiểu lầm"',
    '"misinterpreted": "bị giải thích sai"': '"misinterpret": "dịch sai, hiểu sai"',
    '"misrepresented": "bị trình bày sai"': '"misrepresent": "trình bày sai"',
    '"exaggerated": "bị phóng đại"': '"exaggerate": "phóng đại"',
    '"understated": "bị nói giảm"': '"understate": "nói giảm"',
    '"ignored": "bị bỏ qua"': '"ignore": "bỏ qua, phớt lờ"',
    '"neglected": "bị lơ là"': '"neglect": "lơ là, sao nhãng"',
    '"overlooked": "bị bỏ qua"': '"overlook": "bỏ qua, không chú ý tới"',
    '"forgotten": "bị lãng quên"': '"forget": "quên"',
    '"remembered": "được nhớ lại"': '"remember": "nhớ"',
    '"recalled": "được gọi lại"': '"recall": "gọi lại, nhớ lại"',
    '"reminded": "được nhắc nhở"': '"remind": "nhắc nhở"',
    '"memorized": "được ghi nhớ"': '"memorize": "ghi nhớ"',
    '"learned": "đã học"': '"learn": "học"',
    '"studied": "đã nghiên cứu"': '"study": "nghiên cứu, học"',
    '"researched": "đã nghiên cứu"': '"research": "nghiên cứu"',
    '"discovered": "đã khám phá"': '"discover": "khám phá"',
    '"invented": "đã phát minh"': '"invent": "phát minh"',
    '"created": "đã tạo ra"': '"create": "tạo ra"',
    '"designed": "được thiết kế"': '"design": "thiết kế"',
    '"developed": "được phát triển"': '"develop": "phát triển"',
    '"manufactured": "được sản xuất"': '"manufacture": "sản xuất"',
    '"produced": "được sản xuất"': '"produce": "sản xuất"',
    '"constructed": "được xây dựng"': '"construct": "xây dựng"',
    '"built": "được xây dựng"': '"build": "xây dựng"',
    '"assembled": "được lắp ráp"': '"assemble": "lắp ráp, tập hợp"',
    '"installed": "được cài đặt"': '"install": "cài đặt, lắp đặt"',
    '"implemented": "được thực hiện"': '"implement": "thực hiện, áp dụng"',
    '"executed": "được thi hành"': '"execute": "thi hành, thực thi"',
    '"performed": "được biểu diễn"': '"perform": "biểu diễn, thực hiện"',
    '"conducted": "được tiến hành"': '"conduct": "tiến hành, thực hiện"',
    '"operated": "được vận hành"': '"operate": "vận hành"',
    '"managed": "được quản lý"': '"manage": "quản lý"',
    '"directed": "được chỉ đạo"': '"direct": "chỉ đạo, hướng dẫn"',
    '"supervised": "được giám sát"': '"supervise": "giám sát"',
    '"controlled": "được kiểm soát"': '"control": "kiểm soát"',
    '"regulated": "được quy định"': '"regulate": "quy định, điều chỉnh"',
    '"governed": "bị cai trị"': '"govern": "cai trị, quản lý"'
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open('/Users/nguyetpham/.gemini/antigravity/brain/6f9a1aaa-e3ba-4490-a52a-ca067528b732/scratch/extract_vocab.py', 'w', encoding='utf-8') as f:
    f.write(text)

